FROM starkgate as base

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY set-env.sh ./
COPY start.sh ./
RUN chmod +x start.sh set-env.sh

EXPOSE 80
CMD ["sh", "start.sh"]
