FROM node:16 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV DISABLE_ESLINT_PLUGIN=true

COPY package.json ./
COPY yarn.lock ./
RUN yarn install

COPY . ./
RUN yarn build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY ./scripts/ ./scripts
RUN chmod +x ./scripts/*.sh

EXPOSE 80
CMD ["sh", "./scripts/start.sh"]
