FROM starkgate as base

FROM nginx:stable-alpine

ARG APP_ENV

RUN rm /etc/nginx/conf.d/default.conf
COPY --from=base . /usr/share/nginx/html
COPY ./envs/${APP_ENV}.js /usr/share/nginx/html/env.js
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
