name: 'Deploy helm chart on Pull Request trigger'
on:
  pull_request:

jobs:
  deploy:
    if: contains(github.head_ref, 'refactor') || contains(github.head_ref, 'fix') || contains(github.head_ref, 'feat')
    name: 'Deploy helm chart'
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo 1
