name: Push docker image to GCR reusable workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      gcp_token:
        required: true

jobs:
  build:
    name: Build tag and push docker images to GCR.
    runs-on: ubuntu-latest
    steps:
      - name: Login to Gcloud using starkgate service account.
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: starkware-dev
          service_account_email: starkgate@starkware-dev.iam.gserviceaccount.com
          service_account_key: ${{ secrets.gcp_token }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build dev image and push
        if: ${{ inputs.branch_name == 'refs/heads/dev' }}
        run: |
          docker build . -t ${{ inputs.image_name }} -f ${{ inputs.dockerfile }}
          docker tag ${{ inputs.image_name }} ${{ inputs.image_name }}:${{ github.ref_name }}
          docker push ${{ inputs.image_name }}:${{ github.ref_name }}
          docker push ${{ inputs.image_name }}

      - name: Build production image and push with stable tag
        if: ${{ inputs.branch_name == 'refs/heads/master' || (startsWith(inputs.branch_name, 'refs/tags') && contains(inputs.branch_name, 'patch')) }}
        run: |
          docker build . -t ${{ inputs.image_name }}:stable -f ${{ inputs.dockerfile }}
          docker tag ${{ inputs.image_name }}:stable ${{ inputs.image_name }}:${{ github.ref_name }}
          docker push ${{ inputs.image_name }}:${{ github.ref_name }}
          docker push ${{ inputs.image_name }}:stable
