name: Docker build tag and push frontend images to GCR workflow.

on:
  push:
    tags:
      - v*

jobs:
  push-frontend-image:
    uses: ./.github/workflows/gcr_push_workflow.yml
    with:
      image_name: us.gcr.io/starkware-dev/starknet/starkgate/frontend
      branch_name: ${{ github.event.base_ref }}
      dockerfile: Dockerfile.frontend
    secrets:
      gcp_token: ${{ secrets.STARKGATE_SA }}

  deploy_testnet:
    if: github.event.base_ref == 'refs/heads/test-image-tag'
    needs: [push-frontend-image]
    uses: ./.github/workflows/helm_upgrade_workflow_test.yml
    with:
      app_name: starkgate
      namespace_name: starkgate-goerli
      values_file: deployment/testing.yml
      env_file: .env.testing
      image_tag: ${{ github.ref_name }}-test
    secrets:
      gcp_token: ${{ secrets.STARKGATE_SA }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
