name: Docker build tag and push frontend images to GCR workflow test.

on:
  push:
    tags:
      - v*

jobs:
  deploy_testnet:
    uses: ./.github/workflows/helm_upgrade_workflow_test.yml
    with:
      app_name: starkgate
      namespace_name: starkgate-goerli
      values_file: deployment/testing.yml
      env_file: .env.testing
      image_tag: ${{ github.ref_name }}-test
    secrets:
      gcp_token: ${{ secrets.STARKGATE_SA }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
